import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import LayoutContainer from "@/components/common/LayoutContainer";
import { UserProvider } from "@/context/UserContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <UserProvider>
            <LayoutContainer>
                <div className="w-full h-full m-auto">
                    <div className="max-w-full w-full h-full p-0 flex items-start justify-start">
                        <main className="max-w-full w-full h-full min-h-screen sticky top-0">
                            <div className="page-wrapper max-w-full w-full h-full relative">
                                <div className="App">
                                    <main>
                                        <UserProvider>
                                            <div className="w-full flex justify-center items-center min-h-screen">
                                                {children}
                                            </div>
                                        </UserProvider>
                                    </main>
                                </div>
                            </div>
                        </main>
                    </div>
                </div>
            </LayoutContainer>
        </UserProvider>
    );
}
